### ISSUE TITLE
"compose" doe not work, if first function does not take any parameter

### ISSUE THREAD

**Issue by Lysander** [DasIch/brownie#15]
Consider this snippet:

```
def foo():
    print "Hello"

def bar():
    print "World!"
```

If you now use compose with these two functions, it won't work:

```
compose(foo, bar)()
```

With this error message:

<pre>
World!
ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (4, 0))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)

C:\Dokumente und Einstellungen\nelson\Eigene Dateien\<ipython console> in <modul
e>()

C:\Programme\Python27\lib\site-packages\brownie\functional.pyc in <lambda>(*a, *
*kws)
     28     elif len(functions) == 1:
     29         return functions[0]
---> 30     return reduce(lambda f, g: lambda *a, **kws: f(g(*a, **kws)), functi
ons)
     31
     32

TypeError: foo() takes no arguments (1 given)
</pre>

If you spend **foo** a parameter, it works:

```
def foo(param):
    print "Hello"
```

So of course compose is not really meant to be used for functions without any parameter, but it could be documented anyway I think :-)

**Comment by DasIch** [comment]
This should clarify it https://github.com/DasIch/brownie/commit/63a0404aed35da8ebfed7254866c83713f5ca49d
