### ISSUE TITLE
timeout decorator/context manager

### ISSUE THREAD

**Issue by dag** [DasIch/brownie#16]
```
try:
    with timeout(5):
        return subprocess.Popen(...).communicate(...)
except TimeoutError:
    return None
```

I have working code for this if you're interested (just needs to be turned into a context manager and optionally a decorator).

**Comment by DasIch** [comment]
Working code would definitely be interesting

**Comment by DasIch** [comment]
So thinking about this I see several issues. A context manager wouldn't be really pythonic, a decorator on the other hand doesn't offer you the flexibility to easily change the timeout and you are stuck with it.

In either case using select on the files would be a better solution in the given example and in almost all situations there will similarly be a solution much better suited to the problem.
