### ISSUE TITLE
`LazyList.exhausting` not clear

### ISSUE THREAD

**Issue by cool-RR** [DasIch/brownie#26]
What's up with the `LazyList.exhausting` method?

https://github.com/DasIch/brownie/blob/master/brownie/datastructures/sequences.py#L70

It's really not clear what it does, especially given the fact that it takes no `self` yet it is not decorated as a `staticmethod`. So what is it and what does it to? Some documentation would help.

**Comment by DasIch** [comment]
exhausting is a decorator which is not exposed (the reference is
deleted at the end of the class definition), therefore not a method
and should be considered an implementation detail.

**Comment by cool-RR** [comment]
I see where you use it now. I'd say it's pretty confusing to define it like
it's a method.
