### ISSUE TITLE
Lazy proxies

### ISSUE THREAD

**Issue by dag** [DasIch/brownie#7]
```
>>> now = LazyProxy(datetime.utcnow)
>>> now.second
1
>>> now.second
2
```

Useful for APIs that expect an object and not a callable, but you need the object to behave more like a callable. A `CachedLazyProxy` could also be implemented that calls the callable only the first time, if there's a use case for that.

**Comment by DasIch** [comment]
That is very similar to what is commonly used behind the scenes to implement lazy_gettext, however creating a proper Proxy is very difficult as special methods are looked up directly on the type.

I think it would be more useful to create a factory for Proxies and to implement other common and useful proxies on top of that.

**Comment by dag** [comment]
I'm not sure how such a factory would work. I was basically thinking the behaviour of `werkzeug.LocalProxy` when passed a callable instead of a local.

**Comment by DasIch** [comment]
I'm currently working on the factory part, creating something like `werkzeug.LocalProxy` could be done, using the factory, by creating a simple callback. As an alternative for callbacks contextmanagers can be used as well.

**Comment by DasIch** [comment]
Ignore whatever I wrote before, I've used an entirely new approach and finally added a LazyProxy now. https://github.com/DasIch/brownie/commit/49ae14333abe123f944f682d2f007c0feba71f6b
